postgres_version: 9.3.9
redis_version: 2.8.4
django_version: 1.8
celery_version: 3.1.17
pause_on_success: false
pause_on_failure: true
startup_timeout: 45
python_versions:
  - 2.7.10
  - 3.4.3
environment:
  - i_am_root: false
  - approved_platforms:
    - linux
    - darwin
  - packages:
    - firefox
    - node-less
