postgres_folder:
  darwin: /usr/local/bin/
  linux: /usr/lib/postgresql/9.3/bin/
redis_folder:
  darwin: /usr/local/bin/
  linux: /usr/bin/
python_folder:
  darwin: /usr/local/bin/
  linux: /usr/bin/
postgres_version: 9.3.9
redis_version: 2.8.4
django_version: 1.8
celery_version: 3.1.17
pause_on_success: false
pause_on_failure: true
startup_timeout: 45
python_versions:
  - 2.7.10
  - 3.4.3
environment:
  - approved_platforms:
    - linux
    - darwin
  - freeports:
    - 10025
    - 18080
    - 15432
    - 16379
  - brew:
    - python
    - python3
    - redis
    - libtool
    - automake
    - node
  - debs:
    - python2.7
    - python3.4
    - python-virtualenv
    - python-pip
    - redis-server
    - firefox
    - node-less
    - automake
    - libtool
